; ESP32 老式电视红外遥控器
; 架构沿用 ac-remote：IRremoteESP8266 收发 + 本地网页控制
[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
; 按实际设备修改：
monitor_port = /dev/cu.usbserial-210
upload_port = /dev/cu.usbserial-210
lib_deps =
  crankyoldgit/IRremoteESP8266@^2.8.6
  bblanchon/ArduinoJson@^7.0.0
